// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using practicaWebApiManga;

#nullable disable

namespace practicaWebApiManga.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230530232239_inicios")]
    partial class inicios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("practicaWebApiManga.Entidad.CapituloMangas", b =>
                {
                    b.Property<int>("CapituloMangasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CapituloMangasId"), 1L, 1);

                    b.Property<int>("NumeroCap")
                        .HasColumnType("int");

                    b.Property<int>("OrigenDelMangaid")
                        .HasColumnType("int");

                    b.HasKey("CapituloMangasId");

                    b.HasIndex("OrigenDelMangaid");

                    b.ToTable("capituloMangas");
                });

            modelBuilder.Entity("practicaWebApiManga.Entidad.CapituloSheet", b =>
                {
                    b.Property<int>("CapituloSheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CapituloSheetId"), 1L, 1);

                    b.Property<int>("CapituloMangasId")
                        .HasColumnType("int");

                    b.Property<int>("OrdenDeSheet")
                        .HasColumnType("int");

                    b.Property<string>("urlSheetM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CapituloSheetId", "CapituloMangasId");

                    b.HasIndex("CapituloMangasId");

                    b.ToTable("capituloSheets");
                });

            modelBuilder.Entity("practicaWebApiManga.Entidad.Genero", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneroId"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GeneroId");

                    b.ToTable("generos");

                    b.HasData(
                        new
                        {
                            GeneroId = 1,
                            Nombre = "Acción"
                        },
                        new
                        {
                            GeneroId = 2,
                            Nombre = "Animación"
                        },
                        new
                        {
                            GeneroId = 3,
                            Nombre = "Comedia"
                        },
                        new
                        {
                            GeneroId = 4,
                            Nombre = "Ciencia ficción"
                        },
                        new
                        {
                            GeneroId = 5,
                            Nombre = "Drama"
                        },
                        new
                        {
                            GeneroId = 6,
                            Nombre = "Hentai"
                        },
                        new
                        {
                            GeneroId = 7,
                            Nombre = "Ecchi"
                        });
                });

            modelBuilder.Entity("practicaWebApiManga.Entidad.GeneroOrigenManga", b =>
                {
                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<int>("OrigenDelMangaId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("OrigenManga")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("GeneroId", "OrigenDelMangaId");

                    b.HasIndex("OrigenDelMangaId");

                    b.ToTable("generoOrigenMangas");
                });

            modelBuilder.Entity("practicaWebApiManga.Entidad.ImagenPresentacion", b =>
                {
                    b.Property<int>("ImagenPresentacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImagenPresentacionId"), 1L, 1);

                    b.Property<string>("ImagenPresentacionUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrigenDelMangaId")
                        .HasColumnType("int");

                    b.HasKey("ImagenPresentacionId");

                    b.HasIndex("OrigenDelMangaId")
                        .IsUnique();

                    b.ToTable("imagenPresentacions");
                });

            modelBuilder.Entity("practicaWebApiManga.Entidad.OrigenDelManga", b =>
                {
                    b.Property<int>("OrigenDelMangaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrigenDelMangaId"), 1L, 1);

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrigenDelMangaId");

                    b.ToTable("origenDelMangas");
                });

            modelBuilder.Entity("practicaWebApiManga.Entidad.CapituloMangas", b =>
                {
                    b.HasOne("practicaWebApiManga.Entidad.OrigenDelManga", "OrigenDelManga")
                        .WithMany("CapituloMangas")
                        .HasForeignKey("OrigenDelMangaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrigenDelManga");
                });

            modelBuilder.Entity("practicaWebApiManga.Entidad.CapituloSheet", b =>
                {
                    b.HasOne("practicaWebApiManga.Entidad.CapituloMangas", "CapituloMangas")
                        .WithMany("capituloSheets")
                        .HasForeignKey("CapituloMangasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapituloMangas");
                });

            modelBuilder.Entity("practicaWebApiManga.Entidad.GeneroOrigenManga", b =>
                {
                    b.HasOne("practicaWebApiManga.Entidad.Genero", "Genero")
                        .WithMany("GeneroOrigenMangas")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("practicaWebApiManga.Entidad.OrigenDelManga", "OrigenDelManga")
                        .WithMany("GeneroOrigenMangas")
                        .HasForeignKey("OrigenDelMangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("OrigenDelManga");
                });

            modelBuilder.Entity("practicaWebApiManga.Entidad.ImagenPresentacion", b =>
                {
                    b.HasOne("practicaWebApiManga.Entidad.OrigenDelManga", null)
                        .WithOne("imagenPresentacion")
                        .HasForeignKey("practicaWebApiManga.Entidad.ImagenPresentacion", "OrigenDelMangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("practicaWebApiManga.Entidad.CapituloMangas", b =>
                {
                    b.Navigation("capituloSheets");
                });

            modelBuilder.Entity("practicaWebApiManga.Entidad.Genero", b =>
                {
                    b.Navigation("GeneroOrigenMangas");
                });

            modelBuilder.Entity("practicaWebApiManga.Entidad.OrigenDelManga", b =>
                {
                    b.Navigation("CapituloMangas");

                    b.Navigation("GeneroOrigenMangas");

                    b.Navigation("imagenPresentacion")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
